twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    # créer une variable globale dans Twig afin de paramétrer le répertoire de stockage des images.
    globals :
        app_images_user_directory: '/uploads/images/user'

when@test:
    twig:
        strict_variables: true
